name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 52.204.101.69 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@52.204.101.69 << 'EOF'
            cd my-node-app
            git pull origin main
            npm install
            # Install pm2 if not present
            if ! command -v pm2 &> /dev/null
            then
              sudo npm install -g pm2
            fi
            pm2 restart all || pm2 start server.js
          EOF


